[package]
name = "rustacean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commander = "0.1.2"
win32_notification = "0.1.0"
serde = "1.0.130"
serde_json = "1.0.70"
libc = "0.2.107"
